sudo: enabled
dist: trusty

language: php
php:
  - '7.1'
  - '7.2'

env:
  - NODE_RELEASE=8.x

before_install:
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs

install: 
  - composer install
  - composer require php-coveralls/php-coveralls
  - npm install -g puppeteer

before_script:
  - mkdir -p build/logs

script:
 - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v